/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IconsIndexRouteImport } from './routes/icons/index'
import { Route as IconsPageRouteImport } from './routes/icons/page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsIndexRoute = IconsIndexRouteImport.update({
  id: '/icons/',
  path: '/icons/',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsPageRoute = IconsPageRouteImport.update({
  id: '/icons/page',
  path: '/icons/page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/icons/page': typeof IconsPageRoute
  '/icons': typeof IconsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/icons/page': typeof IconsPageRoute
  '/icons': typeof IconsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/icons/page': typeof IconsPageRoute
  '/icons/': typeof IconsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/icons/page' | '/icons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/icons/page' | '/icons'
  id: '__root__' | '/' | '/icons/page' | '/icons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IconsPageRoute: typeof IconsPageRoute
  IconsIndexRoute: typeof IconsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons/': {
      id: '/icons/'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons/page': {
      id: '/icons/page'
      path: '/icons/page'
      fullPath: '/icons/page'
      preLoaderRoute: typeof IconsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IconsPageRoute: IconsPageRoute,
  IconsIndexRoute: IconsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
